app/models.py
from datetime import datetime

from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash

from app import db

from . import login_manager


class Pitch(db.Model):
    __tablename__ = 'pitches'
    id = db.Column(db.Integer, primary_key = True)
    pitch = db.Column(db.String(400))
    name = db.Column(db.String(20))
    timestamp = db.Column(db.DateTime, index = True, default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    likes = db.relationship('Likes', backref = 'likes', lazy = 'dynamic')
    dislikes = db.relationship('Dislikes', backref = 'dislikes', lazy = 'dynamic')


    def __repr__(self):
        return '<User %r>' %self.pitch

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(50))
    email = db.Column(db.String(255))
    password_hush = db.Column(db.String(128))
    name = db.Column(db.String(20))
    bio = db.Column(db.Text())
    member_since = db.Column(db.DateTime,default=datetime.utcnow)
    pitches = db.relationship('Pitch', backref = 'author', lazy = 'dynamic')
    likes = db.relationship('Likes', backref = 'user', lazy = 'dynamic')
    dislikes = db.relationship('Dislikes', backref = 'dislike', lazy = 'dynamic')


    @property
    def password(self):
        raise AttributeError('password is not a readable input')

    @password.setter
    def password(self,password):
        self.password_hush = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.password_hush,password)

    def __repr__(self) -> str:
        return '<User %r>' % self.username


class Likes(db.Model):
    id = db.Column(db.Integer,primary_key = True)
    upvote = db.Column(db.Integer)
    user_id  = db.Column(db.Integer,db.ForeignKey('users.id'))
    pitch_id = db.Column(db.Integer, db.ForeignKey('pitches.id'))

    def save(self):
        db.session.add(self)
        db.session.commit()
    
    @classmethod
    def get_likes(cls,id):
        upvotes = Dislikes.query.filter_by(pitch_id = id).all()
        return upvotes

class Dislikes(db.Model):
    id = db.Column(db.Integer,primary_key = True)
    downvote = db.Column(db.Integer)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    pitch_id = db.Column(db.Integer,db.ForeignKey('pitches.id'))

    def save(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_dislikes(cls,id):
        downvotes = Dislikes.query.ofilter_by(pitch_id=id).all()
        return downvotes


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
from ast import Sub
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import InputRequired


class PitchForm(FlaskForm):
    pitch = TextAreaField('Enter your pitch')
    name = StringField('Enter your name', validators=[InputRequired()])
    submit = SubmitField('Pitch', validators=[InputRequired()])

class EditProfile(FlaskForm):
    name = StringField('ENter your name')
    bio = TextAreaField('Add bio')
    submoit  =SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

from flask_mail import Mail
from os import *

# from flask_migrate import Migrate
from flask_mail import Mail
# from flask_uploads import UploadSet,configure_uploads,IMAGES


mail = Mail()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
bootstrap = Bootstrap()
db = SQLAlchemy()



def create_app(config_name):

    app = Flask(__name__)
    
    # Initializing configurations
    app.config.from_object(config_options[config_name])

    # Registering Blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    


    return app 

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views,forms,errors

app/main/views.py
from app.main.forms import EditProfile, PitchForm
from app.models import Dislikes, Likes, Pitch, User
from flask import flash, redirect, render_template, url_for
from flask_login import current_user, login_required

from .. import db
from . import main


@main.route('/')
def index():
    return render_template('index.html')

@main.route('/pitches', methods=['GET', 'POST'])
@login_required
def pitches():

    pitch_form = PitchForm()

    if pitch_form.validate_on_submit():
        pitch = Pitch(pitch=pitch_form.pitch.data, name=pitch_form.name.data)
        db.session.add(pitch)
        db.session.commit()
        return redirect(url_for('.pitches'))
    posts = Pitch.query.all()
    return render_template('pitches.html',posts=posts,pitches=pitches, pitch_form=pitch_form)

@main.route('/user/<username>')
def profile(username):
    user = User.query.filter_by(username=username).first()
    posts = user.pitches.all()
    
    return render_template('profile.html', user=user, pitches=posts)

@main.route('/like/<id>', methods=['GET', 'POST'])
@login_required
def like(id):
    get_pitches = Likes.get_likes(id)
    valid_string = f'{current_user.id}:{id}'
    for pitch in get_pitches:
        to_str = f'{pitch}'
        print(valid_string + " " + to_str)
        if valid_string == to_str:
            return redirect(url_for('main.pitches', id=id))
        else:
            continue
    new_vote = Likes(user=current_user, pitch_id=id, like=like(id))
    new_vote.save()
    return redirect(url_for('main.pitches', id=id))


@main.route('/like/<id>', methods=['GET', 'POST'])
@login_required
def dislike(id):
    get_pitches = Dislikes.get_dislikes(id)
    valid_string = f'{current_user.id}:{id}'
    for pitch in get_pitches:
        to_str = f'{pitch}'
        print(valid_string + " " + to_str)
        if valid_string == to_str:
            return redirect(url_for('main.pitches', id=id))
        else:
            continue
    new_vote = Dislikes(dislike=current_user, pitch_id=id)
    new_vote.save()
    return redirect(url_for('main.pitches', id=id))


@main.route('/edit', methods=['GET', 'POST'])
@login_required
def edit():
    form = EditProfile()
    if form.validate_on_submit():
        current_user.username = form.name.data
        current_user.bio = form.bio.data
        db.session.add(current_user._get_current_object())
        db.session.commit()
        flash('Your profile has been update')
        return redirect(url_for('.profile', username = current_user.username))
    form.name.data  = current_user.username
    form.bio.data = current_user.bio
    return render_template('edit.html', form=form)




    

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- font awesome  -->
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
    <!-- favicon -->
    <link rel="shortcut icon" href="{{url_for('static', filename = 'img/favicon.ico')}}" type="image/x-icon">
    <!-- google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400;500;600&family=Poppins:wght@200;300;400;500;600;700&family=Satisfy&display=swap" rel="stylesheet">
    <!-- bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.css" rel="stylesheet" />
    <!-- css  -->
    {% block css %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/style.css')}}">
    {% endblock %}

    <!-- js -->
    {% block script %}
    {% endblock %}
    
    {% extends 'bootstrap/base.html' %}
    {% block title %}
    <title>pitches</title>
    {% endblock %}

</head>
<body>
    {% block navbar %}

    <nav id="main-navbar" class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
        <!-- Container wrapper -->
        <div class="container-fluid">
          <!-- Toggle button -->
          <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#links"
            aria-controls="links" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
          </button>

          <!-- Brand -->
          <a class="navbar-brand" href="/">
            <i class="bi bi-chat-fill">PITCHES</i>
          </a>
          
          <!-- Right links -->
            <ul class="navbar-nav ms-auto d-flex flex-row" >
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('main.index')}}">HOME</a>
                </li>
                {% if current_user.is_authenticated %}
                
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('main.pitches')}}"><i class="bi bi-chat-0"></i> PITCHES</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('main.profile', username=current_user.username)}}"><i class="bi bi-person"></i> PROFILE</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('auth.logout')}}"><i class="fa fa-sign-out" aria-hidden="true"></i> LOG OUT</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('auth.login')}}"><i class="fa fa-sign-in" aria-hidden="true"></i>LOGIN</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('auth.register')}}">SIGN UP</a>
                </li>
                {% endif %}
            </ul>
        </div>
        <!-- Container wrapper -->
      </nav>
    {% endblock %}

    {% block content %}
    {% endblock %}
    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

app/templates/edit.html
{% extends 'base.html' %}

{%block css%}
<link rel="stylesheet" href="{{url_for('static', filename = 'css/edit.css')}}">
{% endblock %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}

<div class="container">
    <div class="form-container">
        <div class="head">
            <h2>EDIT PROFILE</h2>
        </div>
        <div class="fm-body">
            {{wtf.quick_form(form)}}
        </div>
    </div>
</div>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/style.css')}}">
{% endblock css %}



{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-5 content">
            <div class="two"></div>
            <h1>Welcome to Pitches Platform</h1>
            <p>Where you get to engage a pitch for only sixty seconds</p>
            <p>Enjoy!!!</p>
        </div>
        <div class="col-md-7">
            <img class="img-responsive" src="{{url_for('static', filename='img/pitch.png')}}" alt="">
        </div>
    </div>
    <div class="one"></div>
    <a href="{{url_for('main.pitches')}}"><button class="btn btn-primary add">Add Pitch</button></a>
</div>

{% endblock %}

app/templates/pitches.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{%block css%}
<link rel="stylesheet" href="{{url_for('static', filename = 'css/pitches.css')}}">
{% endblock %}


{% block content%}

<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="pitch-head">
                <h1>Write Your Pitch Here</h1>
                <div class="pitch-content">
                    {% for post in posts %}
                    <h5>{{post.pitch}}</h5>
                    <p>{{post.name}}</p>
                    <a href="{{url_for('main.like', id = post.id)}}"><i class="bi bi-hand-thumbs-up"></i></a><span class="custom">{{post.likes.count()}}</span>
                    <a href="{{url_for('main.dislike', id = post.id)}}"><i class="bi bi-hand-thumbs-down"></i></a><span class="custom">{{post.dislikes.count()}}</span>
                    <hr>
                    <a href="">Add Comment</a>
                    <br><br>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="categories">
                <div class="cat-holder">
                    {{wtf.quick_form(pitch_form)}}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock%}

app/templates/profile.html
{% extends 'base.html' %}
{% block css %}
<link rel="stylesheet" href="{{url_for('static', filename='css/profile.css')}}">
{%  endblock %}

{% block content %}
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-success alert-dismissible" role="alert">
    <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    {{message}}
</div>
{% endfor %}
{% endif %}
{% endwith %}

<div class="container">
    <div class="row">
        <div class="col-md-7 cont">
            <h1 class="text-center">My Pitches</h1>
            <h4>{{user.pitches}}</h4>
        </div>
        <div class="col-md-5">
            <div class="image">
                <img src="{{url_for('static', filename = 'images/profile.png')}}" alt="">
            </div>
            <h1>{{user.username}}<i class="bi bi-check-circle"></i></h1>
            <p>{{user.email}}</p>
            <p>{{user.bio}}</p>
            <a href="{{url_for('main.edit')}}"><button class="btn btn-transparent">Edit Profile</button></a>
        </div>
    </div>
</div>
{% endblock %}